### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Fujisan-3776** [Fujisan-3776/protospace-30592#1]
#URL
https://protospace-30592.herokuapp.com/

ご確認よろしくお願い致します。

**Comment by tnk1215** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられました。
後少しですので修正をお願いします！


[修正箇所]
**・ログインしているユーザー自身が投稿したプロトタイプにコメント欄が空の状態で「送信する」を押下すると添付画像のエラーが出てしまう**
→他のユーザーが投稿したプロトタイプではこちらのエラーは発生しませんが、現在ログインしているユーザーが自分の投稿に空のコメントをした時にのみ発生しているようです。自分の投稿にからのコメントをした際にも「コメントが保存されず、かつエラーが出ない状態」になるよう修正をお願い致します。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7
![スクリーンショット 2020-10-16 10 05 57](https://user-images.githubusercontent.com/63444423/96201746-5aef2600-0f98-11eb-9c86-a120ae2c5f98.png)

**Comment by Fujisan-3776** [comment]
ご確認ありがとうございます！

エラーの原因は、削除ボタンを記述しているリンクのパスが間違っていた（対象のプロトタイプのIDが付加されていなかった）ことによるものでした。

内容修正致しましたので、再度ご確認をお願い致します。

**Comment by MoonMaker23** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください

**Comment by Fujisan-3776** [comment]
ご確認ありがとうございました！！
